{
 "title": "DevOps Metrics Github",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pub",
    "label": "Release Date",
    "query": "SELECT  YEAR(release_date) FROM   metricsDB.releases"
   },
   {
    "name": "version",
    "label": "Version",
    "query": "SELECT CONCAT(name, \"###\", DATE_FORMAT(release_date, '%Y-%m-%d')) as release_date FROM metricsDB.releases WHERE name NOT LIKE '%,%' AND name NOT LIKE '%''%'"
   },
   {
    "name": "repo",
    "label": "pull request",
    "query": "Select number From metricsDB.df_pulls"
   }
  ]
 },
 "panels": [
  {
   "title": "Global",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Mean Time to Merge",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT pulls.*, first_commits.first_commit_calc as first_commit_calc\r\nFROM metricsDB.df_pulls pulls\r\nINNER JOIN (\r\n  SELECT repo, number, MIN(commit_date) as first_commit_calc\r\n  FROM metricsDB.df_commits\r\n  GROUP BY repo, number\r\n) first_commits ON pulls.repo= first_commits.repo AND pulls.number = first_commits.number;"
    }
   ]
  },
  {
   "title": "Mean Time to Code",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT pulls.*, first_commits.first_commit_calc as first_commit_calc\r\nFROM metricsDB.df_pulls pulls\r\nINNER JOIN (\r\n  SELECT repo, number, MIN(commit_date) as first_commit_calc\r\n  FROM metricsDB.df_commits\r\n  GROUP BY repo, number\r\n) first_commits ON pulls.repo= first_commits.repo AND pulls.number = first_commits.number;"
    }
   ]
  },
  {
   "title": "Mean Pick-up Time",
   "type": "gauge",
   "description": "Time between release deployments",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT pulls.*, first_reviews.first_review_calc as first_review_calc\r\nFROM metricsDB.df_pulls pulls\r\nINNER JOIN (\r\n  SELECT repo, number, MIN(submitted_at) as first_review_calc\r\n  FROM metricsDB.df_reviews\r\n  WHERE state = \"APPROVED\"\r\n  GROUP BY repo, number\r\n) first_reviews ON pulls.repo= first_reviews.repo AND pulls.number = first_reviews.number;"
    }
   ]
  },
  {
   "title": "Mean time by status per version",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "targets": [
    {
     "rawSql": "SELECT pulls.*, first_commits.first_commit_calc as first_commit_calc\r\nFROM metricsDB.df_pulls pulls\r\nINNER JOIN (\r\n  SELECT repo, number, MIN(commit_date) as first_commit_calc\r\n  FROM metricsDB.df_commits\r\n  GROUP BY repo, number\r\n) first_commits ON pulls.repo= first_commits.repo AND pulls.number = first_commits.number;"
    }
   ]
  },
  {
   "title": "$repo",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "repeat": "repo",
   "targets": [
    {}
   ]
  },
  {
   "title": "Mean time to merge",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT pulls.*, first_commits.first_commit_calc as first_commit_calc\r\nFROM metricsDB.df_pulls pulls\r\nINNER JOIN (\r\n  SELECT repo, number, MIN(commit_date) as first_commit_calc\r\n  FROM metricsDB.df_commits\r\n  GROUP BY repo, number\r\n) first_commits ON pulls.repo= first_commits.repo AND pulls.number = first_commits.number\r\nWHERE pulls.number = $repo;"
    }
   ]
  },
  {
   "title": "Mean Time to Code",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT pulls.*, first_commits.first_commit_calc as first_commit_calc\r\nFROM metricsDB.df_pulls pulls\r\nINNER JOIN (\r\n  SELECT repo, number, MIN(commit_date) as first_commit_calc\r\n  FROM metricsDB.df_commits\r\n  GROUP BY repo, number\r\n) first_commits ON pulls.repo= first_commits.repo AND pulls.number = first_commits.number\r\nWHERE pulls.number = $repo;"
    }
   ]
  },
  {
   "title": "Mean Pick-up Time",
   "type": "gauge",
   "description": "Time between release deployments",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT pulls.*, first_reviews.first_review_calc as first_review_calc\r\nFROM metricsDB.df_pulls pulls\r\nINNER JOIN (\r\n  SELECT repo, number, MIN(submitted_at) as first_review_calc\r\n  FROM metricsDB.df_reviews\r\n  WHERE state = \"APPROVED\"\r\n  GROUP BY repo, number\r\n) first_reviews ON pulls.repo= first_reviews.repo AND pulls.number = first_reviews.number\r\nWHERE pulls.number = $repo;\r\n"
    }
   ]
  },
  {
   "title": "Mean time by status",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "Select commits.* From metricsDB.df_commits commits\r\nwhere commits.number = $repo "
    }
   ]
  }
 ]
}