{
 "title": "DevOps Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pub",
    "label": "Release Date",
    "query": "SELECT  YEAR(release_date) FROM   metricsDB.releases"
   },
   {
    "name": "version",
    "label": "Version",
    "query": "SELECT CONCAT(name, \"###\", DATE_FORMAT(release_date, '%Y-%m-%d')) as release_date FROM metricsDB.releases WHERE name NOT LIKE '%,%' AND name NOT LIKE '%''%'"
   }
  ]
 },
 "panels": [
  {
   "title": "Global",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average Cycle Time (Open -> Released)",
   "type": "gauge",
   "description": "Average time required to delivered from Open to Released",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "metricsDB",
     "rawSql": "SELECT * FROM metricsDB.status_changes",
     "source": "url",
     "type": "uql",
     "uql": "parse-json\r\n| order by \"version\" asc",
     "url": "https://raw.githubusercontent.com/devops-opensource/devops-metrics/main/test_data.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Average Cycle Time (In Progress -> Released)",
   "type": "gauge",
   "description": "Average time required to delivered from In Progress to Published",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "metricsDB",
     "rawSql": "SELECT * FROM metricsDB.status_changes",
     "source": "url"
    }
   ]
  },
  {
   "title": "Release deployment frequency",
   "type": "gauge",
   "description": "Time between release deployments",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "metricsDB",
     "rawSql": "SELECT *,\r\n       (SELECT release_date FROM metricsDB.releases s2\r\n        WHERE s2.release_date < s.release_date\r\n        ORDER BY s2.release_date DESC LIMIT 1) as previous_release\r\nFROM metricsDB.releases s WHERE s.release_date IS NOT NULL ORDER BY s.release_date\r\n",
     "source": "url",
     "type": "uql",
     "uql": "parse-json\r\n| jsonata \"$map($, function($v, $i, $a) {$i=0 ? $merge([{'Previous Version': 'None'}, $v]) : $merge([{'Previous Version': $a[$i-1].release_date}, $v])})\"\r\n| order by \"name\" asc",
     "url": "https://github.com/devops-opensource/devops-metrics/blob/main/releases.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Mean time by status per version",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "targets": [
    {
     "dataset": "metricsDB",
     "rawSql": "SELECT * FROM metricsDB.status_changes ORDER BY version",
     "source": "url",
     "type": "uql",
     "uql": "parse-json\r\n| jsonata \"*[version='$ver']\"\r\n| order by \"version\" asc",
     "url": "https://raw.githubusercontent.com/devops-opensource/devops-metrics/main/test_data.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Version: ${version:text} - Release date: ${version:value}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "repeat": "version",
   "targets": [
    {}
   ]
  },
  {
   "title": "Lead Time (Open -> Released)",
   "type": "gauge",
   "description": "Average time required to deliver from Open to Published. ()",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "metricsDB",
     "rawSql": "SELECT * FROM metricsDB.status_changes WHERE version = '${version:text}'",
     "source": "url",
     "type": "uql",
     "uql": "parse-json\r\n| jsonata \"*[version='$ver']\"\r\n| order by \"version\" asc",
     "url": "https://raw.githubusercontent.com/devops-opensource/devops-metrics/main/test_data.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Lead Time (In Progress -> Released)",
   "type": "gauge",
   "description": "Average time required to deliver from In Progress to Released",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "metricsDB",
     "rawSql": "SELECT * FROM metricsDB.status_changes WHERE version = '${version:text}'",
     "source": "url",
     "type": "uql",
     "uql": "parse-json\r\n| jsonata \"*[version='$ver']\"\r\n| order by \"version\" asc",
     "url": "https://raw.githubusercontent.com/devops-opensource/devops-metrics/main/test_data.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Time since last version",
   "type": "gauge",
   "description": "Time between release deployments",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "metricsDB",
     "rawSql": "SELECT *,\r\n       (SELECT release_date FROM metricsDB.releases s2\r\n        WHERE s2.release_date < s.release_date\r\n        ORDER BY s2.release_date DESC LIMIT 1) as previous_release\r\nFROM metricsDB.releases s WHERE name = '${version:text}' ORDER BY s.release_date\r\n",
     "source": "url",
     "type": "uql",
     "uql": "parse-json\r\n| jsonata \"[$map($, function($v, $i, $a) {$i=0 ? $merge([{'Previous Version': 'None'}, $v]) : $merge([{'Previous Version': $a[$i-1].release_date}, $v])})[name='$ver']]\"",
     "url": "https://github.com/devops-opensource/devops-metrics/blob/main/releases.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Mean time by status",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "metricsDB",
     "rawSql": "SELECT * FROM metricsDB.status_changes WHERE version = '${version:text}'",
     "source": "url",
     "type": "uql",
     "uql": "parse-json\r\n| jsonata \"*[version='$ver']\"\r\n| order by \"version\" asc",
     "url": "https://raw.githubusercontent.com/devops-opensource/devops-metrics/main/test_data.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  }
 ]
}