{
 "title": "DevOps Metrics New Version",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pub",
    "label": "Release Date",
    "query": "SELECT  YEAR(release_date) FROM   metricsDB.releases"
   },
   {
    "name": "project",
    "label": "Project",
    "query": "SELECT DISTINCT project_key\nFROM metricsDB.status_changes"
   },
   {
    "name": "version",
    "label": "Version",
    "query": "SELECT CONCAT(name, \"###\", DATE_FORMAT(release_date, '%Y-%m-%d')) as release_date\nFROM metricsDB.releases releases\nINNER JOIN (\n  SELECT DISTINCT version \n  FROM metricsDB.status_changes status_changes\n) ticket_versions ON ticket_versions.version = releases.name\n WHERE name NOT LIKE '%,%' AND name NOT LIKE '%''%' AND releases.project_key = \"$project\""
   }
  ]
 },
 "panels": [
  {
   "title": "Global",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average Lead Time (Open -> Released)",
   "type": "gauge",
   "description": "Average time required to delivered from Open to Released",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT * FROM metricsDB.status_changes\r\nWHERE project_key = \"$project\""
    }
   ]
  },
  {
   "title": "Average Cycle Time (In Progress -> Released)",
   "type": "gauge",
   "description": "Average time required to delivered from In Progress to Published",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT * FROM metricsDB.status_changes\r\nWHERE project_key = \"$project\""
    }
   ]
  },
  {
   "title": "Release deployment frequency",
   "type": "gauge",
   "description": "Time between release deployments",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT *,\r\n       (SELECT release_date FROM metricsDB.releases s2\r\n        WHERE s2.release_date < s.release_date AND s2.project_key = \"$project\"\r\n        ORDER BY s2.release_date DESC LIMIT 1) as previous_release\r\nFROM metricsDB.releases s \r\nWHERE s.release_date IS NOT NULL AND s.project_key = \"$project\"\r\nORDER BY s.release_date\r\n"
    }
   ]
  },
  {
   "title": "Mean time by status per version",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "targets": [
    {
     "rawSql": "SELECT * \r\nFROM metricsDB.status_changes \r\nWHERE project_key = \"$project\"\r\nORDER BY version"
    }
   ]
  },
  {
   "title": "Average Lead Time (Open -> Released)",
   "type": "gauge",
   "description": "Average time required to delivered from Open to Released",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT *, min(from_date) as min_from_date, max(to_date) as max_to_date\r\nFROM metricsDB.status_changes as status_changes\r\nWHERE project_key = \"$project\"  AND (from_status = \"Open\" OR to_status = \"Released\")\r\nGROUP BY status_changes.key"
    }
   ]
  },
  {
   "title": "Version: ${version:text} - Release date: ${version:value}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "repeat": "version",
   "targets": [
    {}
   ]
  },
  {
   "title": "Lead Time (Open -> Released)",
   "type": "gauge",
   "description": "Average time required to deliver from Open to Published. ()",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT * FROM metricsDB.status_changes \r\nWHERE project_key = \"$project\" AND FIND_IN_SET(\"${version:text}\", version)"
    }
   ]
  },
  {
   "title": "Lead Time (In Progress -> Released)",
   "type": "gauge",
   "description": "Average time required to deliver from In Progress to Released",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT * FROM metricsDB.status_changes WHERE project_key = \"$project\" AND FIND_IN_SET(\"${version:text}\", version)"
    }
   ]
  },
  {
   "title": "Time since last version",
   "type": "gauge",
   "description": "Time between release deployments",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT *,\r\n       (SELECT release_date FROM metricsDB.releases s2\r\n        WHERE s2.release_date < s.release_date\r\n        ORDER BY s2.release_date DESC LIMIT 1) as previous_release\r\nFROM metricsDB.releases s \r\nWHERE s.project_key = \"$project\" AND s.name = \"${version:text}\"\r\nORDER BY s.release_date\r\n"
    }
   ]
  },
  {
   "title": "Mean time by status",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT * FROM metricsDB.status_changes \r\nWHERE project_key = \"$project\" AND FIND_IN_SET(\"${version:text}\", version)"
    }
   ]
  }
 ]
}