{
 "title": "DevOps Metrics Github",
 "time": { "from": "2023-02-02T19:10:03.000Z", "to": "2023-04-19T19:46:57.000Z" },
 "templating": {
  "list": [
   {
    "name": "repo",
    "label": "Repository",
    "query": "SELECT DISTINCT repo\nFROM metricsDB.pulls"
   },
   {
    "name": "pr_number",
    "label": "Pull Request",
    "query": "Select CONCAT(number, \"###\", head_name) as pr_number\nFrom metricsDB.pulls WHERE repo IN ($repo) AND merged is not null;"
   }
  ]
 },
 "panels": [
  {
   "title": "Global",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Mean Time to Merge",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT pulls.*, first_commits.first_commit_calc as first_commit_calc,\r\nTIMESTAMPDIFF(SECOND, first_commit_calc, merged) as TTMSQL\r\nFROM metricsDB.pulls pulls\r\nINNER JOIN (\r\n  SELECT repo, number, MIN(commit_date) as first_commit_calc\r\n  FROM metricsDB.commits\r\n  GROUP BY repo, number\r\n) first_commits ON pulls.repo= first_commits.repo AND pulls.number = first_commits.number\r\nWHERE pulls.repo IN ($repo);"
    }
   ]
  },
  {
   "title": "Mean Time to Code",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT pulls.*, first_commits.first_commit_calc as first_commit_calc\r\nFROM metricsDB.pulls pulls\r\nINNER JOIN (\r\n  SELECT repo, number, MIN(commit_date) as first_commit_calc\r\n  FROM metricsDB.commits\r\n  GROUP BY repo, number\r\n) first_commits ON pulls.repo= first_commits.repo AND pulls.number = first_commits.number\r\nWHERE pulls.repo IN ($repo);"
    }
   ]
  },
  {
   "title": "Mean Pick-up Time",
   "type": "gauge",
   "description": "Time between release deployments",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT pulls.*, first_reviews.first_review_calc as first_review_calc\r\nFROM metricsDB.pulls pulls\r\nINNER JOIN (\r\n  SELECT repo, number, MIN(submitted_at) as first_review_calc\r\n  FROM metricsDB.reviews\r\n  WHERE state LIKE \"%approved%\"\r\n  GROUP BY repo, number\r\n) first_reviews ON pulls.repo= first_reviews.repo AND pulls.number = first_reviews.number\r\nWHERE pulls.repo IN ($repo);"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  YEAR(pr_events.timestamp) AS year_number,\r\n  WEEK(pr_events.timestamp) AS week_number,\r\n  SUM(IF(pr_events.event_type = 'Creation', 1, 0)) AS created_count,\r\n  SUM(IF(pr_events.event_type = 'Merge', 1, 0)) AS merged_count,\r\n  STR_TO_DATE(CONCAT(CONCAT(YEAR(pr_events.timestamp), WEEK(pr_events.timestamp)),' Monday'), '%x%v %W') AS year_week\r\nFROM\r\n  metricsDB.pr_events pr_events\r\nWHERE\r\n  pr_events.event_type IN ('Creation', 'Merge') AND pr_events.timestamp IS NOT NULL AND pr_events.repo IN ($repo)\r\nGROUP BY\r\n  year_number,\r\n  week_number\r\nORDER BY\r\n  year_number,\r\n  week_number;"
    }
   ]
  },
  {
   "title": "Mean Time to Merge",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "targets": [
    {
     "rawSql": "SELECT pulls.*, first_commits.first_commit_calc as first_commit_calc, \r\nAVG(TIMESTAMPDIFF(SECOND, first_commit_calc, pulls.merged)/86400) OVER ( \r\n               ORDER BY merged ASC) AS AVGTTM,\r\n(pulls.merged - first_commit_calc) as TTM\r\nFROM metricsDB.pulls pulls\r\nINNER JOIN (\r\n  SELECT repo, number, MIN(commit_date) as first_commit_calc\r\n  FROM metricsDB.commits\r\n  GROUP BY repo, number\r\n) first_commits ON pulls.repo= first_commits.repo AND pulls.number = first_commits.number\r\nWHERE pulls.merged IS NOT NULL AND pulls.repo IN ($repo);"
    }
   ]
  },
  {
   "title": "Pull Request: ${pr_number:value} - ${pr_number:text}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "repeat": "pr_number",
   "targets": [
    {}
   ]
  },
  {
   "title": "Time to merge",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT pulls.*, first_commits.first_commit_calc as first_commit_calc\r\nFROM metricsDB.pulls pulls\r\nINNER JOIN (\r\n  SELECT repo, number, MIN(commit_date) as first_commit_calc\r\n  FROM metricsDB.commits\r\n  GROUP BY repo, number\r\n) first_commits ON pulls.repo= first_commits.repo AND pulls.number = first_commits.number\r\nWHERE pulls.number = ${pr_number:value} AND pulls.repo IN ($repo);"
    }
   ]
  },
  {
   "title": "Time to Code",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT pulls.*, first_commits.first_commit_calc as first_commit_calc\r\nFROM metricsDB.pulls pulls\r\nINNER JOIN (\r\n  SELECT repo, number, MIN(commit_date) as first_commit_calc\r\n  FROM metricsDB.commits\r\n  GROUP BY repo, number\r\n) first_commits ON pulls.repo= first_commits.repo AND pulls.number = first_commits.number\r\nWHERE pulls.number = ${pr_number:value}  AND pulls.repo IN ($repo);"
    }
   ]
  },
  {
   "title": "Pick-up Time",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT pulls.*, first_reviews.first_review_calc as first_review_calc\r\nFROM metricsDB.pulls pulls\r\nINNER JOIN (\r\n  SELECT repo, number, MIN(submitted_at) as first_review_calc\r\n  FROM metricsDB.reviews\r\n  WHERE state LIKE \"%approved%\"\r\n  GROUP BY repo, number\r\n) first_reviews ON pulls.repo= first_reviews.repo AND pulls.number = first_reviews.number\r\nWHERE pulls.number = ${pr_number:value}  AND pulls.repo IN ($repo);\r\n"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 15, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT pulls.*, first_commits.first_commit_calc as first_commit_calc, review.first_review\r\nFROM metricsDB.pulls pulls\r\nINNER JOIN (\r\n  SELECT repo, number, MIN(commit_date) as first_commit_calc\r\n  FROM metricsDB.commits\r\n  GROUP BY repo, number\r\n) first_commits ON pulls.repo= first_commits.repo AND pulls.number = first_commits.number\r\nINNER JOIN (\r\n  SELECT repo, number, MIN(submitted_at) as first_review\r\n  FROM metricsDB.reviews\r\n  GROUP BY repo, number\r\n) review ON pulls.repo= review.repo AND pulls.number = review.number\r\nWHERE pulls.number = ${pr_number:value}  AND pulls.repo IN ($repo);"
    }
   ]
  }
 ]
}