{
 "title": "DevOps Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ver",
    "label": "Version",
    "query": "SELECT  * FROM   metricsDB.releases"
   },
   {
    "name": "pub",
    "label": "Version",
    "query": "SELECT  YEAR(release_date) FROM   metricsDB.releases"
   }
  ]
 },
 "panels": [
  {
   "title": "Global",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average Cycle time (Open -> Resolved)",
   "type": "stat",
   "description": "Average time required to delivered from Open to Released",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "metricsDB",
     "rawSql": "SELECT * FROM metricsDB.status_changes",
     "source": "url",
     "type": "uql",
     "uql": "parse-json\r\n| order by \"version\" asc",
     "url": "https://raw.githubusercontent.com/devops-opensource/devops-metrics/main/test_data.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Average Cycle time (In Progress -> Resolved)",
   "type": "stat",
   "description": "Average time required to delivered from In Progress to Published",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "metricsDB",
     "rawSql": "SELECT * FROM metricsDB.status_changes LIMIT 50 ",
     "source": "url",
     "type": "uql",
     "uql": "parse-json\r\n| order by \"version\" asc",
     "url": "https://raw.githubusercontent.com/devops-opensource/devops-metrics/main/test_data.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Release deployment frequency",
   "type": "stat",
   "description": "Time between release deployments",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "metricsDB",
     "rawSql": "SELECT * FROM metricsDB.releases LIMIT 50 ",
     "source": "url",
     "type": "uql",
     "uql": "parse-json\r\n| jsonata \"$map($, function($v, $i, $a) {$i=0 ? $merge([{'Previous Version': 'None'}, $v]) : $merge([{'Previous Version': $a[$i-1].release_date}, $v])})\"\r\n| order by \"name\" asc",
     "url": "https://github.com/devops-opensource/devops-metrics/blob/main/releases.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Version : $ver",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "repeat": "ver",
   "targets": [
    {}
   ]
  },
  {
   "title": "Cycle Time (Open -> Released)",
   "type": "stat",
   "description": "Average time required to deliver from Open to Published",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "metricsDB",
     "rawSql": "SELECT * FROM metricsDB.status_changes LIMIT 50 ",
     "source": "url",
     "type": "uql",
     "uql": "parse-json\r\n| jsonata \"*[version='$ver']\"\r\n| order by \"version\" asc",
     "url": "https://raw.githubusercontent.com/devops-opensource/devops-metrics/main/test_data.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Cycle Time (In Progress -> Released)",
   "type": "stat",
   "description": "Average time required to deliver from In Progress to Released",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "metricsDB",
     "rawSql": "SELECT * FROM metricsDB.status_changes LIMIT 50 ",
     "source": "url",
     "type": "uql",
     "uql": "parse-json\r\n| jsonata \"*[version='$ver']\"\r\n| order by \"version\" asc",
     "url": "https://raw.githubusercontent.com/devops-opensource/devops-metrics/main/test_data.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Deployment frequency",
   "type": "stat",
   "description": "Time between release deployments",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "metricsDB",
     "rawSql": "SELECT * FROM metricsDB.releases LIMIT 50 ",
     "source": "url",
     "type": "uql",
     "uql": "parse-json\r\n| jsonata \"[$map($, function($v, $i, $a) {$i=0 ? $merge([{'Previous Version': 'None'}, $v]) : $merge([{'Previous Version': $a[$i-1].release_date}, $v])})[name='$ver']]\"",
     "url": "https://github.com/devops-opensource/devops-metrics/blob/main/releases.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  }
 ]
}