name: devops-metrics-ci

on:
  push:
    branches:
      - "**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements/dev_requirements.txt ]; then pip install -r requirements/dev_requirements.txt ; fi
          pip install _submodules/splunk --upgrade

      - name: Run unit tests and build coverage report
        run: coverage run -m pytest -v tests

  quality-gate:
    runs-on: ubuntu-latest
    needs: build
    name: Quality gate
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Publish code coverage to code climate
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_COVERAGE_ID }}
        with:
          coverageCommand: coverage xml -o coverage.xml # explicitly exporting coverage file to be read by coverage report command.
          coverageLocations: coverage.py
          debug: true

  publish:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: "Publish to docker"
    needs: quality-gate
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/devops-metrics:latest
    
